# Generated by Django 5.2 on 2025-04-17 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Internships',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('company', models.CharField()),
                ('location', models.CharField()),
                ('deadline', models.DateField()),
                ('apply', models.URLField()),
            ],
        ),
    ]
