# Generated by Django 5.2 on 2025-04-20 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internships',
            name='apply',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='internships',
            name='company',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internships',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='internships',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
